In [8]:
#creating loading ,saving,nd arrays using np

import numpy as np
arr=np.arange(10)
np.save("some array",arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load("some array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez('array archive.npz',a=arr,b=arr)
arch=np.load('array archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1=np.arange(10)
np.save("some array",arr1)
arr2=np.arange(20)
np.save("some array",arr2)
np.savez('array archive.npz',a=arr1,b=arr2)
arch=np.load('array archive.npz')
arch['a']


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])